# https://taskfile.dev

version: '3'

env:
  # GOMOCACHE: $GOMODCACHE

tasks:
  default: 
    deps: [all]

  all:
    cmds:
      - task: env-up
      - task: start-app  
      - task: run
  
  env-up:
    desk: "Start Docker"
    cmds:
      - docker-compose -f docker-compose.yml up --always-recreate-deps --detach --build
      - go run ./cmd/envtool
      - migrate -path migrations -database "postgresql://wimm:wimm@localhost/wimm?sslmode=disable" up

  env-stop:
    desk: "Stop Docker"
    cmds:
      - docker-compose -f docker-compose.yml down

  start-app:
    cmds:
      - task: build
      - task: run

  build:
    cmds:
      - go build -o ./bin/wimm -v ./cmd/wimm
    
  run:
    cmds:
      - ./bin/wimm
    # silent: true
